config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pokemons#index"

  resources :pokemons do
    resources :moves
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/move.rb
class Move < ApplicationRecord
  belongs_to :pokemon
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :moves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/moves_controller.rb
require 'pokemon/pokemon_client'

class MovesController < ApplicationController
    def index
        @pokemon = Pokemon.find_by(name: params[:pokemon_id])
        if @pokemon.moves.empty?
            pokemon_moves = ::PokemonSupport::PokemonClient.moves_by_pokemon(params[:pokemon_id])
            pokemon_moves.each { |move| @pokemon.moves.create(move) }
        end
        @moves = @pokemon.moves
    end
end

app/controllers/pokemons_controller.rb
require 'pokemon/pokemon_client'

class PokemonsController < ApplicationController
  def index
    if params[:name]
      if Pokemon.find_by(name: params[:name])
        @pokemon = Pokemon.find_by(name: params[:name])
      else
        pokemon = ::PokemonSupport::PokemonClient.pokemon_by_name(params[:name])
        @pokemon = Pokemon.new(pokemon)
        @pokemon.save
      end
      redirect_to pokemon_path(@pokemon.name)
    end
  end

  def show
    if params[:contiguious]
      pokemon_name = ::PokemonSupport::PokemonClient.id_by_name(params[:contiguious]) + params[:difference].to_i
    elsif params[:name]
      pokemon_name = params[:name]
    else
      pokemon_name = params[:id]
    end

    if Pokemon.find_by(name: pokemon_name)
      @pokemon = Pokemon.find_by(name: pokemon_name)
    else
      pokemon = ::PokemonSupport::PokemonClient.pokemon_by_name(pokemon_name)
      @pokemon = Pokemon.new(pokemon)
      @pokemon.save
    end

    if params[:contiguious] or params[:name]
      redirect_to pokemon_path(@pokemon.name)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moves/_move.html.erb
<div class="move">
    <h2><strong><%= move.name.capitalize %></strong></h2>
    <p><strong>Power: </strong><%= move.power %></p>
    <p><strong>Description: </strong><%= move.description %></p>
    <p><strong>Category: </strong><%= move.category %></p>
</div>

app/views/moves/index.html.erb
<%= content_for :screen do %>
    <h1 class="pokemon-name"><%= @pokemon.name.capitalize %></h1>
    <img src=<%= @pokemon.image %> class = "pokemon-image-moves" />
<% end %>
<%= content_for :buttons do %>
    <%= form_with(url: pokemon_path(@pokemon.name), method: :get) do |form| %>
            <%= form.submit "", class: "strong-blue-button" %>
    <% end %>
    <button class="green-large-button" />
    <button class="yellow-large-button" />
<% end %>
<%= content_for :moves do %>
    <h1 class= "pokemon-name">Moves</h1>
    <%= render @moves %>
<% end %>
<%= render "pokemons/pokedex" %>

app/views/pokemons/_pokedex.html.erb
<body>
<div class="container">
<div class="pokeball-container">
  <%= image_tag("Pokeball.png", alt: "Pokeball", class: "pokeball") %>
</div>
    <div class="pokedex">
      <div class="top">
        <div class="color-buttons">
        <%= form_with(url: root_path, method: :get) do |form| %>
            <%= form.submit "", class: "blue-button" %>
        <% end %>
        <button class="green-button"></button>
        <button class="red-button"></button>
        <button class="yellow-button"></button>
      </div>
        <div class="screen">
            <%= yield :screen %>
        </div>
      </div>
        <div class="color-buttons-down">
          <%= yield :buttons %>
        </div>

      <%= form_with(method: :get) do |form| %>
      <div class="search">
        <%= form.text_field :name, placeholder: "Find Pokemon" %>
        <%= form.submit "", class: "Buscar" %>
      </div>
      <% end %>

    </div>
    <div class="back-case">
      <div class="topv2">
        <div class="screenv2">
          <%= yield :moves %>
        </div>
      </div>
    
    </div>
  </div>


<script>
  pokeballContainer = document.querySelector(".pokeball-container");

  pokeballContainer.style.display = "flex";

  setTimeout(function () {
    pokeballContainer.style.display = "none";
  }, 300);
</script>

</body>

app/views/pokemons/index.html.erb
<%= content_for :screen do %>
    <h1 class="pokemon-name">Pokedex</h1>
    <%= image_tag("pokeball.gif", alt: "Pokeball", class: "pokeballGif") %>
<% end %>
<%= content_for :buttons do %>
    <button class="strong-blue-button"/>
    <button class="green-large-button" />
    <button class="yellow-large-button" />
<% end %>
<%= content_for :moves do %>
    <div class="logo-container">
        <%= image_tag("pokemon_logo_v3.webp", alt: "Logo", class: "rotated-image") %>
    </div>
<% end %>
<%= render "pokedex" %>

app/views/pokemons/show.html.erb
<%= content_for :screen do %>
    <h1 class="pokemon-name"><%= @pokemon.name.capitalize %></h1>
    <img src=<%= @pokemon.image %>  class="pokemon-image" />
    <ul class="no-bullets">
        <li>Height: <%= @pokemon.height %> </li>
        <li>Weight: <%= @pokemon.weight %> </li>
        <li>Base Experience: <%= @pokemon.base_experience %> </li>
    </ul>
<% end %>
<%= content_for :buttons do %>
    <%= form_with(url: pokemon_moves_path(@pokemon.name), method: :get) do |form| %>
        <%= form.submit "", class: "strong-blue-button" %>
    <% end %>

    <%= form_with(method: :get) do |form| %>
        <%= form.hidden_field :contiguious, value: params[:id] %>
        <%= form.hidden_field :difference, value: -1 %>
        <%= form.submit "", class: "green-large-button" %>
    <% end %>

    <%= form_with(method: :get) do |form| %>
        <%= form.hidden_field :contiguious, value: params[:id] %>
        <%= form.hidden_field :difference, value: 1 %>
        <%= form.submit "", class: "yellow-large-button" %>
    <% end %>

<% end %>
<%= content_for :moves do %>
    <div class="logo-container">
        <%= image_tag("pokemon_logo_v3.webp", alt: "Logo", class: "rotated-image") %>
    </div>
  <% end %>
  <%= render "pokedex" %>
  